### PR TITLE
Create ost.yml

### PR DESCRIPTION
**Pull request by avlitman**
adds "/ost" comment trigger for OST

### CODE REVIEW

**Review by mwperina — APPROVED** [review]
+1

**Comment by michalskrivanek** [comment]
you should really do that for "approved" only, please replace with the commented line:)

**Comment by avlitman** [comment]
> you should really do that for "approved" only, please replace with the commented line:)

Hi Michal, I tried pushing using the commend line and git this error:

 ! [remote rejected] add-ost-check -> add-ost-check (refusing to allow a Personal Access Token to create or update workflow `.github/workflows/ost.yml` without `workflow` scope)

**Review by michalskrivanek — APPROVED** [review]

**Pull request merged**
