### PR TITLE
build: ovirt-engine-metrics-1.5.0

### PR DESCRIPTION
**Pull request by avlitman**
Signed-off-by: Aviv Litman <alitman@redhat.com>

### CODE REVIEW

**Comment by sandrobonazzola** [comment]
This is failing due to 
```
-D 'release_suffix '
```

I would suggest to change the automation for not passing this parameter for this PR and restore it after the build.

**Comment by avlitman** [comment]
> This is failing due to
> 
> ```
> -D 'release_suffix '
> ```
> 
> I would suggest to change the automation for not passing this parameter for this PR and restore it after the build.

Done, thank you!

**Review by sandrobonazzola — APPROVED** [review]
LGTM

**Comment by avlitman** [comment]
@mwperina Hi Martin same results, you think it's better to update the build-srpm.sh as in dwh ?

**Pull request merged**
